version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
    depends_on:
      - php80

  mysql:
   image: mysql
   restart: always
   container_name: db-mysql
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: blankfactor
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: bfuser
     MYSQL_PASSWORD: bfpassword
   volumes:
    - ./dump:/docker-entrypoint-initdb.d

  php80:
    container_name: php80
    build:
      context: ./php
      dockerfile: PHP80.Dockerfile
    hostname: php80
    extra_hosts:
      - "blankfactor.test:10.1.0.100"
    volumes:
      - ./app:/var/www/html:cached
